Rename stuff

diff --git a/beetle b/beetle
--- a/beetle
+++ b/beetle
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 if [[ $# != 2 ]] ; then
-    >&2 echo -e "Usage: $0 <action> <sourcecode-file>\nPrank Example: $0 prank controller.js\nFix Example: $0 fix controller.js"
+    >&2 echo -e "Usage: $0 <action> <sourcecode-file>\nPrank Example: $0 sting controller.js\nFix Example: $0 cure controller.js"
     exit 1
 fi
 
@@ -10,13 +10,13 @@ shopt -s nocasematch
 
 
 SPACE_CHAR=' '
-INVISIBLE_CHAR='‌‌ '
+INVISIBLE_CHAR='‌ '
 
 ## Validates the input
 validate_input () {
 
-    if [[ "$1" != "prank" ]] && [[ "$1" != "fix" ]] ; then
-        >&2 echo -e "Invalid action \"$1\". Allowed actions are \"prank\" and \"fix\""
+    if [[ "$1" != "sting" ]] && [[ "$1" != "cure" ]] ; then
+        >&2 echo -e "Invalid action \"$1\". Allowed actions are \"sting\" and \"cure\""
         exit 1
     fi
 
@@ -26,15 +26,15 @@ validate_input () {
     fi
 }
 
-## Applies the prank on file i.e replaces the spaces
+## Applies the sting on file i.e replaces the spaces
 ## available in file with invisible char
-prank_file () {
+sting_file () {
     sed -i -e "s/$SPACE_CHAR/$INVISIBLE_CHAR/g" $1
 }
 
 ## Fixes the file i.e. replaces the invisible 
 ## char back to spaces
-fix_file () {
+cure_file () {
     sed -i -e "s/$INVISIBLE_CHAR/$SPACE_CHAR/g" $1
 }
 
@@ -45,13 +45,13 @@ FILE=$2
 
 validate_input $ACTION $FILE
 
-if [[ $ACTION = "prank" ]] ; then
-    
-    # Pranking the same file twice won't work
-    # So fix it before applying the prank
-    fix_file $FILE
-    prank_file $FILE
+if [[ $ACTION = "sting" ]] ; then
 
-elif [[ $ACTION = "fix" ]]; then
-    fix_file $FILE
+    # Pranking the same file twice won't work
+    # So cure it before applying the sting
+    cure_file $FILE
+    sting_file $FILE
+
+elif [[ $ACTION = "cure" ]]; then
+    cure_file $FILE
 fi
